service: crud-users

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: arn:aws:dynamodb:us-east-1:184440761998:table/users

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dynamodb-local

package:
  individually: true
  patterns:
    - "!*/**"

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  find-user:
    handler: src/functions/users/find.handler
    package:
      patterns:
        - "src/functions/users/create.js"
    events:
      - http:
          path: users/{id}
          method: GET
  create-user:
    handler: src/functions/users/create.handler
    package:
      patterns:
        - "src/functions/users/create.js"
    events:
      - http:
          path: users
          method: POST
  update-user:
    handler: src/functions/users/update.handler
    package:
      patterns:
        - "src/functions/users/update.js"
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-user:
    handler: src/functions/users/delete.handler
    package:
      patterns:
        - "src/functions/users/delete.js"
    events:
      - http:
          path: users/{id}
          method: DELETE