service: crud-users

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript
functions:
  get-users:
    handler: greeting.hello
    events:
      - http:
          path: users
          method: GET