service: crud-users

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: arn:aws:dynamodb:us-east-1:184440761998:table/users

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  find-user-by-id:
    handler: src/functions/users/find-by-id.handler
    events:
      - http:
          path: users/{id}
          method: GET
  create-user:
    handler: src/functions/users/create.handler
    events:
      - http:
          path: users
          method: POST